local Inventory = require("Utils").Inventory

local ItemQuickhackRecipes = {}

function ItemQuickhackRecipes.GiveAllQuickhackRecipes()
    local ids = {
        "Recipe_ContagionProgram",
        "Recipe_ContagionLvl2Program",
        "Recipe_ContagionLvl3Program",
        "Recipe_ContagionLvl4Program",
        "Recipe_LocomotionMalfunctionProgram",
        "Recipe_LocomotionMalfunctionLvl2Program",
        "Recipe_LocomotionMalfunctionLvl3Program",
        "Recipe_LocomotionMalfunctionLvl4Program",
        "Recipe_MadnessLvl3Program",
        "Recipe_MadnessLvl4Program",
        "Recipe_DisableCyberwareProgram",
        "Recipe_DisableCyberwareLvl2Program",
        "Recipe_DisableCyberwareLvl3Program",
        "Recipe_GrenadeExplodeLvl3Program",
        "Recipe_GrenadeExplodeLvl4Program",
        "Recipe_MemoryWipeLvl2Program",
        "Recipe_MemoryWipeLvl3Program",
        "Recipe_OverheatProgram",
        "Recipe_OverheatLvl2Program",
        "Recipe_OverheatLvl3Program",
        "Recipe_OverheatLvl4Program",
        "Recipe_PingProgram",
        "Recipe_PingLvl2Program",
        "Recipe_PingLvl3Program",
        "Recipe_PingLvl4Program",
        "Recipe_BlindLvl2Program",
        "Recipe_BlindLvl3Program",
        "Recipe_BlindLvl4Program",
        "Recipe_BlindProgram",
        "Recipe_CommsCallInProgram",
        "Recipe_CommsCallInLvl3Program",
        "Recipe_EMPOverloadProgram",
        "Recipe_EMPOverloadLvl2Program",
        "Recipe_EMPOverloadLvl3Program",
        "Recipe_EMPOverloadLvl4Program",
        "Recipe_CommsNoiseProgram",
        "Recipe_CommsNoiseLvl2Program",
        "Recipe_CommsNoiseLvl3Program",
        "Recipe_CommsNoiseLvl4Program",
        "Recipe_SuicideLvl3Program",
        "Recipe_SuicideLvl4Program",
        "Recipe_BrainMeltLvl2Program",
        "Recipe_BrainMeltLvl3Program",
        "Recipe_BrainMeltLvl4Program",
        "Recipe_SystemCollapseLvl3Program",
        "Recipe_SystemCollapseLvl4Program",
        "Recipe_WeaponMalfunctionProgram",
        "Recipe_WeaponMalfunctionLvl2Program",
        "Recipe_WeaponMalfunctionLvl3Program",
        "Recipe_WeaponMalfunctionLvl4Program",
        "Recipe_WhistleProgram",
        "Recipe_WhistleLvl2Program",
        "Recipe_WhistleLvl3Program",
        "Recipe_WhistleLvl0Program",
        "Recipe_CommsCallInLvl2Program",
        "Recipe_WhistleLvl1Program",
        "Recipe_OverheatLvl1Program",
        "Recipe_BlindLvl1Program",
        "Recipe_CommsCallInLvl1Program",
        "Recipe_EMPOverloadLvl1Program",
        "Recipe_WhistleLvl4Program",
        "Recipe_WhistleLvl4PlusPlusProgram",
        "Recipe_ContagionLvl4PlusPlusProgram",
        "Recipe_LocomotionMalfunctionLvl4PlusPlusProgram",
        "Recipe_MadnessLvl4PlusPlusProgram",
        "Recipe_DisableCyberwareLvl4Program",
        "Recipe_DisableCyberwareLvl4PlusPlusProgram",
        "Recipe_GrenadeExplodeLvl4PlusPlusProgram",
        "Recipe_MemoryWipeLvl4Program",
        "Recipe_MemoryWipeLvl4PlusPlusProgram",
        "Recipe_OverheatLvl4PlusPlusProgram",
        "Recipe_PingLvl4PlusPlusProgram",
        "Recipe_BlindLvl4PlusPlusProgram",
        "Recipe_CommsCallInLvl4Program",
        "Recipe_CommsCallInLvl4PlusPlusProgram",
        "Recipe_EMPOverloadLvl4PlusPlusProgram",
        "Recipe_CommsNoiseLvl4PlusPlusProgram",
        "Recipe_SuicideLvl4PlusPlusProgram",
        "Recipe_BrainMeltLvl4PlusPlusProgram",
        "Recipe_SystemCollapseLvl4PlusPlusProgram",
        "Recipe_WeaponMalfunctionLvl4PlusPlusProgram"
    }

    for _, v in ipairs(ids) do
        Inventory.GiveItem("Items." .. v, 1)
    end
end

return ItemQuickhackRecipes
