local Inventory = require("Utils").Inventory

local ItemClothingRecipes = {}

function ItemClothingRecipes.GiveAllClothingRecipes()
    local ids = {
        "UncommonVestRecipe",
        "RareFormalShoesRecipe",
        "LegendaryTechRecipe",
        "EpicLooseShirtRecipe",
        "UncommonVisorRecipe",
        "RareFormalPantsRecipe",
        "EpicShortsRecipe",
        "EpicHatRecipe",
        "LegendaryFormalSkirtRecipe",
        "RareShortsRecipe",
        "UncommonFormalShoesRecipe",
        "LegendaryShortsRecipe",
        "LegendaryShirtRecipe",
        "UncommonCapRecipe",
        "LegendaryFormalShoesRecipe",
        "EpicFormalJacketRecipe",
        "LegendaryTShirtRecipe",
        "UncommonBalaclavaRecipe",
        "LegendaryJacketRecipe",
        "RareJacketRecipe",
        "LegendaryCapRecipe",
        "UncommonHelmetRecipe",
        "UncommonPantsRecipe",
        "RareFormalJacketRecipe",
        "LegendaryCasualShoesRecipe",
        "Recipe_GOG_Galaxy_TShirt_Epic",
        "Recipe_GOG_Galaxy_TShirt_Legendary",
        "EpicPantsRecipe",
        "RareBootsRecipe",
        "LegendaryPantsRecipe",
        "EpicGlassesRecipe",
        "UncommonFormalSkirtRecipe",
        "EpicScarfRecipe",
        "EpicCasualShoesRecipe",
        "UncommonDressRecipe",
        "UncommonShirtLooseRecipe",
        "EpicFormalSkirtRecipe",
        "UncommonJacketRecipe",
        "Recipe_Q005_Johnny_Glasses_Epic",
        "Recipe_Q005_Johnny_Glasses_Legendary",
        "Recipe_Q005_Johnny_Pants_Epic",
        "Recipe_Q005_Johnny_Pants_Legendary",
        "Recipe_Q005_Johnny_Shoes_Epic",
        "Recipe_Q005_Johnny_Shoes_Legendary",
        "Recipe_Q005_Johnny_Shirt_Epic",
        "Recipe_Q005_Johnny_Shirt_Legendary",
        "EpicHelmetRecipe",
        "LegendaryJumpsuitRecipe",
        "UncommonTechRecipe",
        "EpicMaskRecipe",
        "EpicFormalShoesRecipe",
        "LegendaryBootsRecipe",
        "RareCoatRecipe",
        "LegendaryHatRecipe",
        "UncommonMaskRecipe",
        "EpicUndershirtRecipe",
        "EpicFormalShirtRecipe",
        "EpicBootsRecipe",
        "RareVestRecipe",
        "RareShirtRecipe",
        "RareTShirtRecipe",
        "LegendaryTightJumpsuitRecipe",
        "UncommonFormalShirtRecipe",
        "UncommonBootsRecipe",
        "Recipe_SQ031_Samurai_Jacket_Epic",
        "Recipe_SQ031_Samurai_Jacket_Legendary",
        "RareCasualShoesRecipe",
        "LegendaryScarfRecipe",
        "LegendaryVestRecipe",
        "UncommonShirtRecipe",
        "UncommonUndershirtRecipe",
        "RareHelmetRecipe",
        "UncommonFormalPantsRecipe",
        "RareUndershirtRecipe",
        "EpicCapRecipe",
        "EpicCoatRecipe",
        "RareGlassesRecipe",
        "LegendaryVisorRecipe",
        "UncommonCasualShoesRecipe",
        "LegendaryGlassesRecipe",
        "RareScarfRecipe",
        "RareMaskRecipe",
        "RareTechRecipe",
        "EpicTShirtRecipe",
        "LegendaryFormalPantsRecipe",
        "RareHatRecipe",
        "RarePantsRecipe",
        "Recipe_GOG_DLC_Jacket_Epic",
        "Recipe_GOG_DLC_Jacket_Legendary",
        "Recipe_GOG_DLC_TShirt_Epic",
        "Recipe_GOG_DLC_TShirt_Legendary",
        "EpicVisorRecipe",
        "Recipe_GOG_Galaxy_TShirt",
        "Recipe_GOG_DLC_TShirt",
        "Recipe_Jacket_19_basic_04_DLC_Epic",
        "Recipe_Jacket_19_basic_04_DLC_Legendary",
        "Recipe_Jacket_20_basic_01_DLC_Epic",
        "Recipe_Jacket_20_basic_01_DLC_Legendary",
        "Recipe_Jacket_19_basic_04_DLC",
        "Recipe_Jacket_20_basic_01_DLC",
        "Recipe_GOG_DLC_Jacket"
    }

    for _, v in ipairs(ids) do
        Inventory.GiveItem("Items." .. v, 1)
    end
end

return ItemClothingRecipes
